//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 11:14:32 PM IDT 
//


package EncryptionWithJAXB.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mainAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subAlgoruthm1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subAlgoruthm2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mainAlgorithm",
    "subAlgoruthm1",
    "subAlgoruthm2"
})
@XmlRootElement(name = "defaulEencryptionAlgorithm")
public class DefaulEencryptionAlgorithm {

    @XmlElement(required = true)
    protected String mainAlgorithm;
    @XmlElement(required = true)
    protected String subAlgoruthm1;
    @XmlElement(required = true)
    protected String subAlgoruthm2;

    /**
     * Gets the value of the mainAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainAlgorithm() {
        return mainAlgorithm;
    }

    /**
     * Sets the value of the mainAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainAlgorithm(String value) {
        this.mainAlgorithm = value;
    }

    /**
     * Gets the value of the subAlgoruthm1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubAlgoruthm1() {
        return subAlgoruthm1;
    }

    /**
     * Sets the value of the subAlgoruthm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubAlgoruthm1(String value) {
        this.subAlgoruthm1 = value;
    }

    /**
     * Gets the value of the subAlgoruthm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubAlgoruthm2() {
        return subAlgoruthm2;
    }

    /**
     * Sets the value of the subAlgoruthm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubAlgoruthm2(String value) {
        this.subAlgoruthm2 = value;
    }

}
