//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 07:51:36 PM IDT 
//


package reportwithJAXB.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the reportwithJAXB.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: reportwithJAXB.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportForDirectory }
     * 
     */
    public ReportForDirectory createReportForDirectory() {
        return new ReportForDirectory();
    }

    /**
     * Create an instance of {@link ReportForDirectory.FilesInDirectory }
     * 
     */
    public ReportForDirectory.FilesInDirectory createReportForDirectoryFilesInDirectory() {
        return new ReportForDirectory.FilesInDirectory();
    }

    /**
     * Create an instance of {@link ReportForDirectory.FilesInDirectory.File }
     * 
     */
    public ReportForDirectory.FilesInDirectory.File createReportForDirectoryFilesInDirectoryFile() {
        return new ReportForDirectory.FilesInDirectory.File();
    }

    /**
     * Create an instance of {@link ReportForDirectory.FilesInDirectory.File.IfSucceeded }
     * 
     */
    public ReportForDirectory.FilesInDirectory.File.IfSucceeded createReportForDirectoryFilesInDirectoryFileIfSucceeded() {
        return new ReportForDirectory.FilesInDirectory.File.IfSucceeded();
    }

    /**
     * Create an instance of {@link ReportForDirectory.FilesInDirectory.File.IfFailed }
     * 
     */
    public ReportForDirectory.FilesInDirectory.File.IfFailed createReportForDirectoryFilesInDirectoryFileIfFailed() {
        return new ReportForDirectory.FilesInDirectory.File.IfFailed();
    }

}
